const Projects: React.FC = () => {
  return (
    <div id="projects" className="tab-content">
      <h2 className="section-title highlight-text">Projects</h2>
      
      <div className="project-item">
        <div className="item-title">
          <a href="https://github.com/orgs/GaitAnalysis/repositories" target="_blank" rel="noopener noreferrer">Gait analysis with single camera setup</a>
        </div>
        <div className="item-subtitle">Graduation Project</div>
        <div className="item-date">Sep 2022 - May 2023</div>
        <div className="item-description">
          A simpler and more cost-efficient way of performing gait analysis with just the use of a single mobile phone camera, where we achieved 97% accuracy in classifying if the person has a potential neurodegenerative disease or not using OpenPose for generating keypoint gait data from the videos, and an inference LSTM for classifying based on the key points generated by OpenPose.
        </div>
      </div>

      <div className="project-item">
        <div className="item-title">
          <a href="https://github.com/mucansever/kmeans-recommender" target="_blank" rel="noopener noreferrer">How to build a recommendation system?</a>
        </div>
        <div className="item-subtitle">Experimental Project</div>
        <div className="item-date">Jan 2023</div>
        <div className="item-description">
          Post about building a recommendation system in minutes using a simple K-Means clustering model.
        </div>
      </div>

      <div className="project-item">
        <div className="item-title">
          <a href="https://github.com/mucansever/image4location" target="_blank" rel="noopener noreferrer">NLP based photo geo-location</a>
        </div>
        <div className="item-subtitle">Experimental Project</div>
        <div className="item-date">May 2022</div>
        <div className="item-description">
          An app that guesses the location of the uploaded images using a CLIP model fine-tuned on images from Google Maps Places API. This NLP-based approach yielded 73% accuracy on 1000 random images from Google Maps.
        </div>
      </div>

      <div className="project-item">
        <div className="item-title">
          <a href="https://github.com/mucansever/huffman_coding" target="_blank" rel="noopener noreferrer">Huffman Encoder/Decoder</a>
        </div>
        <div className="item-subtitle">Experimental Project</div>
        <div className="item-date">Feb 2021</div>
        <div className="item-description">
          Basic compression algorithm written on C++.
        </div>
      </div>
    </div>
  );
};

export default Projects;
